### ISSUE TITLE
Use buffer in Swift for Cobra VAD

### ISSUE THREAD

**Issue by Tryad0** [Picovoice/flutter-voice-processor#11]
In Flutter I get the buffer from voiceProcessor.addListener(). When I access those buffer in Swift for Cobra VAD I'm getting an error like 
"Fatal error: Unexpectedly found nil while unwrapping an Optional value".

Thanks!

**Comment by laves** [comment]
If you are recording and using the audio in ios, you should use our [ios-voice-processor](https://github.com/Picovoice/ios-voice-processor). It is not advisable to take audio obtained with the flutter voice processor and pass it back to native code.
