### ISSUE TITLE
Breaking changes without major version bump

### ISSUE THREAD

**Issue by out0f0rder** [Picovoice/flutter-voice-processor#16]
Changing .getVoiceProcessor() to .instance() and moving frameLength, sampleRate to start() is pretty big deal and painful breaking change. 
At least that requires major version change

**Comment by laves** [comment]
Appreciate the feedback and apologies for the confusion. At Picovoice, we tend to use the second number for upgrades (which may include API changes) and the first number for larger systematic/engine changes. In this case, our audio recorder packages had slightly different APIs and we brought them more in line with each other. The underlying audio recording engine did not change.
