### ISSUE TITLE
Flutter Voice Processor Issue: Platform channel messages must be sent on the platform thread

### ISSUE THREAD

**Issue by jtdLab** [Picovoice/flutter-voice-processor#17]
### Expected behaviour

No errors

### Actual behaviour

The 'flutter_voice_processor_frame_events' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

### Steps to reproduce the behaviour

Use flutter_voice_processor in a flutter application.

**Comment by jtdLab** [comment]
This might be helpful:

https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-obj-c-tab#channels-and-platform-threading

**Comment by ksyeo1010** [comment]
What platform did you get this error on? Did you get crashes on the platform you tried (ios or android)?

**Comment by jtdLab** [comment]
I ran into it on iOS did not test Android yet. The app did not crash but showed the above warning/error. Seems to be related with newer Flutter versions being more strict with the threads where communication with native platform happens. Flutterfire had similar issue see [here](https://github.com/firebase/flutterfire/pull/11650).

**Comment by ksyeo1010** [comment]
Ok, thanks for reporting. We will work on a patch in the following weeks but cannot tell you an exact estimate on when a patch will be available.

**Comment by jtdLab** [comment]
Great. Thanks a lot.

**Comment by sonnyvesali** [comment]
would this have anything to do with it not working in a production environment?

I don't have any logs, but it works in my simulator in a debug bundle but fails in a production iOS environment?

**Comment by laves** [comment]
@sonnyvesali - can you open a new issue regarding this? Some additional details on reproducibility and environment setup would be very helpful. I can't say if this is related or a different issue.

**Comment by sonnyvesali** [comment]
@laves  it was some other issue unrelated to the bug, forgot to include my leopard access key in my production .env ci/cd pipeline, silly me, thank you for the prompt reply!

**Comment by laves** [comment]
@jtdLab - this issue should have been addressed in the latest release (`1.1.1`). Can you confirm that the warning is no longer present for you?

**Comment by jtdLab** [comment]
Its gone on my side
