### ISSUE TITLE
Possibility to add web plugin?

### ISSUE THREAD

**Issue by timmolter** [Picovoice/flutter-voice-processor#19]
**Is your feature request related to a problem? Please describe.**
Yes. One major selling point of Flutter, is one codebase, many platforms. This package doesn't support web.

**Describe the solution you'd like**
Could this package be expanded to support web?

**Describe alternatives you've considered**
Writing a completely separate codebase for web, but I really don't want to.

**Additional context**
[Here](https://github.com/Canardoux/flutter_sound/blob/master/flutter_sound_web/lib/flutter_sound_web.dart) is a different package that has added a web plugin for microphone streaming. (Disclaimer: I have not tested it) As I am a complete newbie to writing Flutter plugins, I just want to ask if you think this is even possible, first, and secondly, do you have any plans to implement it?

**Comment by laves** [comment]
Unfortunately, this is not on the roadmap as we already have a separate package for web ([web-voice-processor](https://github.com/Picovoice/web-voice-processor)) and Picovoice Flutter SDKs don't currently support Flutter Web.
