### ISSUE TITLE
Flutter Voice Processor Issue: Can not record on iOS simulator

### ISSUE THREAD

**Issue by jtdLab** [Picovoice/flutter-voice-processor#22]
When recording on an iOS Simulator with iOS 17.2 the recorded data is a stream of [0,0,0,0,...] .
Permission for microphone is granted.

**Comment by laves** [comment]
@jtdLab - does this happen with the [example](https://github.com/Picovoice/flutter-voice-processor/tree/main/example)? I just ran the example on an iOS 17.2 simulator and it is working as expected. We'll need a reproducable example.

**Comment by jtdLab** [comment]
The example works on android emulator. But has the described error on iOS 17.2 simulator. Looks like thats an issue on my machine with xcode not allowing mic usage. so im closing this
