### ISSUE TITLE
It can detect the user speaking

### ISSUE THREAD

**Issue by dunghacknicktao** [Picovoice/flutter-voice-processor#25]
Hello,

Forgive me for not having enough time to study your library thoroughly. 
Please allow me to ask quickly, can your library detect whether the user is speaking or not?

Because this is a useful feature to integrate into conversation-related projects.

Best regards,

**Comment by albho** [comment]
No, flutter voice processor is designed to handle audio processing. To detect whether a user is speaking, you should use [cobra](https://github.com/Picovoice/cobra). If you meant to label different speakers in a conversation, consider using [falcon](https://github.com/Picovoice/falcon) instead. Unfortunately though, note that neither of these currently have a flutter binding, if that's the SDK you're working on.
