### ISSUE TITLE
Voice processor seems to mix up the audio player channels after recording

### ISSUE THREAD

**Issue by ashlog** [Picovoice/flutter-voice-processor#4]
Related issue: https://github.com/Picovoice/flutter-voice-processor/issues/2

I am using a flutter video player plugin and the video player seems to be playing through the earpiece speaker instead of the regular phone speaker even after stopping the recorder and disposing it entirely. I've also tried a different plugin for playing audio instead of video_player and the issue still persists.

1. Start any type of media.
2. Media plays on regular speaker.
3. Call voice processor start();
4. Call voice processor stop();
5. Try to start the same media again
6. Media plays on earpiece speaker instead of regular speaker.

Repository to isolate this issue: https://github.com/muhatashim/flutter-voice-processor-video-player-demo

**Comment by laves** [comment]
Thanks for reporting. Is this issue present on Android and iOS?

**Comment by ashlog** [comment]
> Thanks for reporting. Is this issue present on Android and iOS?

Seems to be iOS only from what I remember.

**Comment by laves** [comment]
Okay, thanks. I think I know what may be causing this. We changed some iOS audio session settings to deal with issue#2, but I think we added one in there that is causing the issue you are experiencing. We'll have a fix for this shortly.

**Comment by ashlog** [comment]
> Okay, thanks. I think I know what may be causing this. We changed some iOS audio session settings to deal with issue#2, but I think we added one in there that is causing the issue you are experiencing. We'll have a fix for this shortly.

Hey, just wondering if there's been any updates into this issue.

**Comment by laves** [comment]
This issue has been scheduled to be taken care of first thing next week - apologies for the delay.

**Comment by laves** [comment]
@ashlog, update to latest and the issue should be fixed.

**Comment by ashlog** [comment]
> @ashlog, update to latest and the issue should be fixed.

Fantastic, thanks for the quick fix! I just verified it as working now.
