### ISSUE TITLE
BluetoothSco() feature availing

### ISSUE THREAD

**Issue by 7ij** [Picovoice/flutter-voice-processor#6]
If we can use bluetooth headset to capture audio with flutter voice processor  it would be great. Can this feature be added?

**Comment by laves** [comment]
@7ij that is definitely a feature we'd like to add, but I can't promise we'll get to it right away. I'll leave this issue open to track it, and we'll try to find time to add it at some point.

**Comment by 7ij** [comment]
@kenarsa Is the feature added. I don't see about this feature in change logs

**Comment by kenarsa** [comment]
@7ij sorry for the confusion. closed as not planned. If you like to add this feature please feel free to submit a PR
